[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "kjamoi-store"
version = "0.2.0"
description = "A unified CLI package manager for Debian-based systems"
authors = [{name = "Ahmed Khalil"}]
requires-python = ">=3.8"
readme = "README.md"

[project.scripts]
kjamoi-store = "kjamoi.main:main"